services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_ENCRYPTION_KEY
        value: some-long-random-string
      - key: GENERIC_TIMEZONE
        value: UTC
